name: CD - Deploy to Kubernetes

on:
  workflow_run:
    workflows: ["CI - Build & Push Docker"]
    types: [ "completed" ]

permissions:
  contents: read

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # -------------------------
      # VARIÁVEIS (LINUX)
      # -------------------------
      - name: Set vars
        id: vars
        run: |
          echo "IMAGE=eduardoavila26/monitor" >> $GITHUB_OUTPUT
          echo "TAG_SHA=${GITHUB_SHA:0:7}" >> $GITHUB_OUTPUT

          if [ -z "${{ secrets.K8S_NAMESPACE }}" ]; then
            echo "❌ ERRO: o secret K8S_NAMESPACE está vazio!"
            exit 1
          fi

          echo "NAMESPACE=${{ secrets.K8S_NAMESPACE }}" >> $GITHUB_OUTPUT

      - name: Debug namespace
        run: |
          echo "Namespace escolhido: ${{ steps.vars.outputs.NAMESPACE }}"

      # -------------------------
      # INSTALAÇÃO DO KUBECTL
      # -------------------------
      - name: Setup kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'latest'

      # -------------------------
      # KUBECONFIG PARA LINUX
      # -------------------------
      - name: Configure kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 -d > ~/.kube/config

      # -------------------------
      # CRIA NAMESPACE SE NÃO EXISTE
      # -------------------------
      - name: Create namespace if not exists
        run: |
          kubectl get ns ${{ steps.vars.outputs.NAMESPACE }} || \
          kubectl create ns ${{ steps.vars.outputs.NAMESPACE }}

      # -------------------------
      # APLICA MANIFESTOS
      # -------------------------
      - name: Apply base manifests
        run: |
          kubectl apply -n ${{ steps.vars.outputs.NAMESPACE }} -f k8s/service.yaml
          kubectl apply -n ${{ steps.vars.outputs.NAMESPACE }} -f k8s/prometheus-deployment.yaml
          kubectl apply -n ${{ steps.vars.outputs.NAMESPACE }} -f k8s/grafa
