name: CD - Deploy to Kubernetes

on:
  workflow_run:
    workflows: ["CI - Build & Push Docker"]
    types: ["completed"]

permissions:
  contents: read

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # -------------------------
      # VARIÁVEIS (POWERSHELL)
      # -------------------------
      - name: Set vars
        id: vars
        shell: pwsh
        run: |
          echo "IMAGE=eduardoavila26/monitor" >> $env:GITHUB_OUTPUT
          echo "TAG_SHA=$($env:GITHUB_SHA.Substring(0,7))" >> $env:GITHUB_OUTPUT

          if (-not "${{ secrets.K8S_NAMESPACE }}") {
            Write-Host "❌ ERRO: Secret K8S_NAMESPACE não definido!"
            exit 1
          }

          echo "NAMESPACE=${{ secrets.K8S_NAMESPACE }}" >> $env:GITHUB_OUTPUT

      - name: Debug namespace
        shell: pwsh
        run: |
          Write-Host "Namespace detectado: ${{ steps.vars.outputs.NAMESPACE }}"

      # -------------------------
      # KUBECTL
      # -------------------------
      - name: Setup kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'latest'

      # -------------------------
      # CONFIGURE KUBECONFIG (WINDOWS)
      # -------------------------
